Class {
	#name : 'AllTestFailTest',
	#superclass : 'MockTest',
	#category : 'TestRunner-FakeTests',
	#package : 'TestRunner-FakeTests'
}

{ #category : 'tests' }
AllTestFailTest >> testFail1 [

	self assert: false
]

{ #category : 'tests' }
AllTestFailTest >> testFail2 [

	self assert: false
]

{ #category : 'tests' }
AllTestFailTest >> testFail3 [

	self assert: false
]

{ #category : 'tests' }
AllTestFailTest >> testFail4 [

	self assert: false
]
